# Generated by Django 3.2.4 on 2021-06-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='start',
        ),
    ]
