# Generated by Django 3.2.4 on 2021-06-24 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopapi', '0002_rename_datetime_appointment_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
