# Generated by Django 3.2.4 on 2021-06-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershopapi', '0003_auto_20210624_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='services',
            new_name='appointment_services',
        ),
    ]
